"""empty message

Revision ID: 75e46e1df0a3
Revises: 5c94293a7174
Create Date: 2024-03-20 23:21:15.929135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e46e1df0a3'
down_revision: Union[str, None] = '5c94293a7174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
