"""add fields  status and online_at at Users

Revision ID: 99ef245bdce4
Revises: 84b575ec6fc6
Create Date: 2024-06-10 19:03:18.766944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ef245bdce4'
down_revision: Union[str, None] = '84b575ec6fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM('offline', 'online', name='userstatusenum')
    status_enum.create(op.get_bind())
    
    op.add_column('user', sa.Column('status', status_enum, server_default='offline', nullable=False))
    op.add_column('user', sa.Column('online_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'online_at')
    
    status_enum = postgresql.ENUM('offline', 'online', name='userstatusenum')
    status_enum.drop(op.get_bind())